---
title: "Resultados"
author: "carlos rios"
date: "Wednesday, April 08, 2015"
output: pdf_document
---

```{r}
library(ggplot2)
```

```{r}
ratingReducido.result<-read.csv("C:/Users/Usuarioç/Desktop/carlos/Tesis/datasets/foursquare/resultados/resultadosUBCFTodosJAIIO.csv")
comparacion<-read.csv("C:/Users/Usuarioç/Desktop/carlos/Tesis/datasets/foursquare/resultados/comparacion_datos_reducidos.csv",sep = ";")
```

```{r}
ratingReducido.result$metodo<-paste(ratingReducido.result$Similitud,
                                    ratingReducido.result$TVecinos,
                                    ratingReducido.result$Nvecinos,
                                    ratingReducido.result$Threshold,sep="-")

ratingReducido.result<-ratingReducido.result[,c("metodo","Mae","Rms")]
str(ratingReducido.result)
ratingReducido.result$metodo[1]<-"C-T-06"
ratingReducido.result$metodo[2]<-"C-T-07"
ratingReducido.result$metodo[3]<-"C-T-08"
ratingReducido.result$metodo[4]<-"C-T-09"
ratingReducido.result$metodo[5]<-"C-KF-10"
ratingReducido.result$metodo[6]<-"C-kF-60"
ratingReducido.result$metodo[7]<-"C-kF-120"
ratingReducido.result$metodo[8]<-"C-KF-ALL"
ratingReducido.result$metodo[9]<-"C-KFF-10"
ratingReducido.result$metodo[10]<-"C-KFF-60"
ratingReducido.result$metodo[11]<-"C-KFF-120"
ratingReducido.result$metodo[12]<-"C-KFF-ALL"
ratingReducido.result$metodo[13]<-"S-T-06"
ratingReducido.result$metodo[14]<-"S-T-07"
ratingReducido.result$metodo[15]<-"S-T-08"
ratingReducido.result$metodo[16]<-"S-T-09"

ratingReducido.result$metodo<-as.factor(ratingReducido.result$metodo)
ratingReducido.result$metodo <- factor(ratingReducido.result$metodo, levels = ratingReducido.result$metodo[order(ratingReducido.result$Mae)])


```


```{r}
ggplot(data=ratingReducido.result, aes(x=metodo,y=Mae))+ 
    geom_bar(stat="identity",position=position_dodge())+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
comparacion
```

